/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': 'var(--color-on-surface)',
        'on-primary': 'var(--color-on-primary)',
        'error': 'var(--color-error)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'on-error': 'var(--color-on-error)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-container': 'var(--color-surface-container)',
        'background': 'var(--color-background)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'secondary': 'var(--color-secondary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'outline': 'var(--color-outline)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-background': 'var(--color-on-background)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'tertiary': 'var(--color-tertiary)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface': 'var(--color-surface)',
        'primary': 'var(--color-primary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'error-container': 'var(--color-error-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'primary-container': 'var(--color-primary-container)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        margin: '24px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['Montserrat', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        'label-md': ['Montserrat', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'body-md': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
