/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'brand-primary': '#4f46e5',
        'brand-primary-dark': '#4338ca',
        'brand-secondary': '#6366f1',
        'brand-tertiary': '#7c3aed',
        'brand-tertiary-light': '#ede9fe',
        background: 'var(--background)',
        surface: 'var(--surface)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        'primary-container': 'var(--primary-container)',
        secondary: 'var(--secondary)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-container': 'var(--color-surface-container)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-background': 'var(--color-on-background)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        tertiary: 'var(--color-tertiary)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'error-container': 'var(--color-error-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
      },
      fontFamily: {
        sans: ['"DM Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['Fraunces', 'ui-serif', 'Georgia', 'Cambria', 'serif'],
        'label-md': ['"DM Sans"', 'sans-serif'],
        'headline-md': ['Fraunces', 'serif'],
        'headline-lg': ['Fraunces', 'serif'],
        'body-md': ['"DM Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
