export const MOCK_COURSES = [
  {
    id: 'c1',
    title: 'Full-Stack Web Development',
    description: 'Learn modern web development from HTML/CSS to React and Node.js.',
    category: 'Web Development',
    level: 'Beginner',
    price: 4999,
    teacher_id: 'mock-teacher-id',
    users: { name: 'Professor Smith', avatar_url: 'https://ui-avatars.com/api/?name=Professor+Smith&background=10B981&color=fff' },
    total_students: 247,
    rating: 4.8,
    total_lessons: 12,
    duration_hours: 24,
    tags: ['React', 'Node.js', 'Express', 'Supabase'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c2',
    title: 'Data Structures & Algorithms',
    description: 'Master computer science fundamentals and prepare for coding interviews.',
    category: 'Computer Science',
    level: 'Intermediate',
    price: 3999,
    teacher_id: 'mock-teacher-id',
    users: { name: 'Professor Smith', avatar_url: 'https://ui-avatars.com/api/?name=Professor+Smith&background=10B981&color=fff' },
    total_students: 189,
    rating: 4.6,
    total_lessons: 15,
    duration_hours: 30,
    tags: ['DSA', 'Algorithms', 'Trees', 'Graphs'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c3',
    title: 'Machine Learning Fundamentals',
    description: 'Build predictive models using Python, scikit-learn, and TensorFlow.',
    category: 'AI & ML',
    level: 'Advanced',
    price: 5999,
    teacher_id: 'mock-teacher-id',
    users: { name: 'Professor Smith', avatar_url: 'https://ui-avatars.com/api/?name=Professor+Smith&background=10B981&color=fff' },
    total_students: 134,
    rating: 4.9,
    total_lessons: 20,
    duration_hours: 40,
    tags: ['Machine Learning', 'Python', 'AI'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c4',
    title: 'Advanced React Patterns',
    description: 'Deep dive into performance, custom hooks, and state management in React.',
    category: 'Web Development',
    level: 'Advanced',
    price: 2999,
    teacher_id: 'mock-teacher-id',
    users: { name: 'Professor Smith', avatar_url: 'https://ui-avatars.com/api/?name=Professor+Smith&background=10B981&color=fff' },
    total_students: 277,
    rating: 4.7,
    total_lessons: 10,
    duration_hours: 15,
    tags: ['React', 'TypeScript', 'Redux'],
    is_published: true,
    created_at: new Date().toISOString(),
  }
];

export const MOCK_LESSONS = [
  { id: 'l1', title: 'Introduction & Setup', type: 'video', order_index: 1 },
  { id: 'l2', title: 'State Management Overview', type: 'pdf', order_index: 2 },
  { id: 'l3', title: 'Hands-on Coding Quiz', type: 'quiz', order_index: 3 },
  { id: 'l4', title: 'Assignment 1 Details', type: 'assignment', order_index: 4 },
];

export const MOCK_SESSIONS = [
  {
    id: 's1',
    course_id: 'c1',
    teacher_id: 'mock-teacher-id',
    title: 'Web Dev: Advanced React',
    room_id: 'classroom_c1_session1',
    scheduled_at: new Date().toISOString(),
    status: 'live',
  },
  {
    id: 's2',
    course_id: 'c2',
    teacher_id: 'mock-teacher-id',
    title: 'DSA: Graph Algorithms',
    room_id: 'classroom_c2_session1',
    scheduled_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
  },
  {
    id: 's3',
    course_id: 'c1',
    teacher_id: 'mock-teacher-id',
    title: 'Office Hours',
    room_id: 'classroom_c1_office',
    scheduled_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
  }
];

export const MOCK_MEMBERS = [
  { id: 'e1', student_id: 'mock-student-id', users: { name: 'Alex Johnson', email: 'alex@nexlearn.com', role: 'student' } },
  { id: 'e2', student_id: 's2', users: { name: 'Priya Sharma', email: 'priya@nexlearn.com', role: 'student' } },
  { id: 'e3', student_id: 's3', users: { name: 'Jordan Lee', email: 'jordan@nexlearn.com', role: 'student' } },
  { id: 'e4', student_id: 's4', users: { name: 'Marcus Brown', email: 'marcus@nexlearn.com', role: 'student' } },
];
