import { LayoutDashboard, Video, ClipboardCheck, UserCheck, BarChart3, Award, Bot } from 'lucide-react';
import { motion } from 'framer-motion';
import { use3DTilt, useCursorGlow } from '../hooks/useCardEffects';
import studentIllustration from '../assets/illustrations/undraw_online-learning_tgmv.svg';
import educatorIllustration from '../assets/illustrations/undraw_teaching_58yg.svg';
import adminIllustration from '../assets/illustrations/undraw_maintenance_4unj.svg';

const dashboardCards = [
  {
    label: 'Student Portal',
    color: 'primary',
    icon: LayoutDashboard,
  },
  {
    label: 'Educator Hub',
    color: 'secondary',
    icon: Video,
  },
  {
    label: 'Admin Console',
    color: 'tertiary',
    icon: ClipboardCheck,
  },
];

const features = [
  {
    icon: Bot,
    title: 'AI Tutor 24/7',
    description: 'Personalized Socratic guidance that helps you find answers through reasoning, not just shortcuts.',
    color: 'primary',
  },
  {
    icon: Video,
    title: 'Live Classroom',
    description: 'High-fidelity video streaming with integrated real-time code execution and shared whiteboards.',
    color: 'secondary',
  },
  {
    icon: ClipboardCheck,
    title: 'Smart Assignments',
    description: 'Auto-graded assignments with qualitative feedback generated by domain-specific AI models.',
    color: 'tertiary',
  },
  {
    icon: UserCheck,
    title: 'Attendance Tracking',
    description: 'Biometric-ready, automated attendance that lets teachers focus on pedagogy, not bookkeeping.',
    color: 'primary',
  },
  {
    icon: BarChart3,
    title: 'Progress Analytics',
    description: 'Deep-dive visualizations of student engagement, learning velocity, and retention metrics.',
    color: 'secondary',
  },
  {
    icon: Award,
    title: 'Certificates',
    description: 'Blockchain-verified credentials issued instantly upon course mastery, shareable with the world.',
    color: 'tertiary',
  },
];

export function DashboardPreview() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, scale: 0.95 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: { duration: 0.6 },
    },
  };

  return (
    <section id="platform" className="py-32 px-6 bg-surface-container-low">
      <div className="max-w-7xl mx-auto mb-20 text-center reveal">
        <h2 className="font-headline-lg text-4xl md:text-6xl mb-6 text-on-surface">A unified platform for everyone</h2>
        <p className="font-body-md text-on-surface-variant">Tailored experiences for every stakeholder in the learning ecosystem.</p>
      </div>

      <motion.div
        className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6"
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: '-50px' }}
      >
        {dashboardCards.map((card, idx) => {
          const Icon = card.icon;
          return (
            <motion.div key={idx} variants={itemVariants} className="glass rounded-3xl p-1 overflow-hidden group hover:scale-[1.02] transition-transform border-outline-variant/30 reveal stagger-1 card-lift">
              <div className="bg-surface-container-high rounded-[calc(1.5rem-4px)] p-6 h-full border border-outline-variant/10">
                <div className="flex items-center justify-between mb-8">
                  <span className={`font-label-md uppercase tracking-widest font-bold text-${card.color}`}>{card.label}</span>
                  {idx === 0 && <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></div>}
                  {idx === 1 && (
                    <div className="flex gap-1">
                      <div className="w-2 h-2 rounded-full bg-blue-400"></div>
                      <div className="w-2 h-2 rounded-full bg-blue-400/50"></div>
                    </div>
                  )}
                  {idx === 2 && <Icon className="w-4 h-4 text-tertiary icon-rotate" />}
                </div>
                <div className="space-y-4">
                  {idx === 0 && (
                    <div className="h-64 bg-surface-container/30 rounded-xl flex items-center justify-center p-4">
                      <img src={studentIllustration} alt="Student Portal" className="w-full h-full object-contain filter drop-shadow-md" />
                    </div>
                  )}
                  {idx === 1 && (
                    <div className="h-64 bg-surface-container/30 rounded-xl flex items-center justify-center p-4">
                      <img src={educatorIllustration} alt="Educator Hub" className="w-full h-full object-contain filter drop-shadow-md" />
                    </div>
                  )}
                  {idx === 2 && (
                    <div className="h-64 bg-surface-container/30 rounded-xl flex items-center justify-center p-4">
                      <img src={adminIllustration} alt="Admin Console" className="w-full h-full object-contain filter drop-shadow-md" />
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          );
        })}
      </motion.div>
    </section>
  );
}

export function FeaturesSection() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.6 },
    },
  };

  return (
    <section id="resources" className="py-32 px-6 relative">
      <div className="max-w-7xl mx-auto text-center mb-20 reveal">
        <h2 className="font-headline-lg text-4xl md:text-6xl mb-6 text-on-surface">Everything You Need</h2>
        <p className="font-body-md text-on-surface-variant max-w-xl mx-auto">
          A comprehensive suite of intelligence tools powered by cutting-edge neural networks.
        </p>
      </div>

      <motion.div
        className="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6"
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: '-50px' }}
      >
        {features.map((feature, idx) => {
          const Icon = feature.icon;
          const colorClass = `text-${feature.color}`;
          const bgColorClass = `bg-${feature.color}/10`;
          const { ref: tiltRef, transform, handleMouseMove: handleTiltMove, handleMouseLeave: handleTiltLeave } = use3DTilt();
          const { ref: glowRef, glowPosition, handleMouseMove: handleGlowMove } = useCursorGlow();

          return (
            <motion.div
              key={idx}
              variants={itemVariants}
              ref={tiltRef}
              onMouseMove={handleTiltMove}
              onMouseLeave={handleTiltLeave}
              style={{ transform }}
              className={`glass p-8 rounded-3xl hover:bg-surface-variant/30 transition-all border-outline/10 hover:border-${feature.color}/20 group bg-surface-container-low/50 reveal stagger-1 cursor-glow-card blur-reveal`}
            >
              <div
                ref={glowRef}
                onMouseMove={handleGlowMove}
                style={{
                  background: `radial-gradient(300px circle at ${glowPosition.x}px ${glowPosition.y}px, rgba(216, 188, 234, 0.15), transparent 40%)`,
                } as React.CSSProperties}
                className="absolute inset-0 pointer-events-none"
              />
              <div className={`w-12 h-12 rounded-xl ${bgColorClass} flex items-center justify-center ${colorClass} mb-6 transition-transform icon-bounce`}>
                <Icon className="w-6 h-6" />
              </div>
              <h4 className="font-headline-md mb-3 text-on-surface">{feature.title}</h4>
              <p className="font-body-md text-on-surface-variant leading-relaxed">{feature.description}</p>
            </motion.div>
          );
        })}
      </motion.div>
    </section>
  );
}
